Blockly.Msg.set_BT_Type = "設定藍牙模式為"
Blockly.Msg.BT_name = "名稱"
Blockly.Msg.data_available = "是否從藍牙接收到資料?"
Blockly.Msg.recieve_data = "讀取藍牙設備資料(數值)"
Blockly.Msg.send_data = "傳送資料"
Blockly.Msg.on_bluetooth = "到藍牙裝置"